exp:
  root_ckpt_dir: './checkpoint_dir'
  device: 'cuda:0'

vqvae_name: 'hrvqvae'  # set to your trained HRVQVAE experiment name (exp.name in train_hrvqvae.yaml)

repeat_time: 20

data:
  name: 'humanml3d'
  root_dir: '/nas2/data/dpfla3573/code/MoScale/dataset/HumanML3D'
